### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by siteleas** [iotacasts/starter#1]
I clone the repository then I try npm install and the following errors appear:

npm WARN saveError ENOENT: no such file or directory, open '/usr/local/ampps/www/iotatest/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/ampps/www/iotatest/package.json'
npm WARN iotatest No description
npm WARN iotatest No repository field.
npm WARN iotatest No README data
npm WARN iotatest No license field.

**Comment by siteleas** [comment]
I discovered that the problem was that I didn't change to the iotacasts-starter folder before performing the npm install. My mistake. Thanks.

**Comment by harby** [comment]
Glad you figured it out. Let me know if you have any other issues. Happy to help!
